databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_LEY
        sync: false
      - key: DATABASE_URL
        formDatabase:
          name: postgres
          property: connectionString
    ipAllowList: []
    plan: free
    maxemoryPolicy: noeviction
